import 'dart:typed_data';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../../data/models/customer_model.dart';
import '../../data/models/profile_model.dart';
import '../../data/models/transaction_model.dart';

class StatementPdfGenerator {
  static final _money = NumberFormat('#,##0.00', 'en_PH');
  static final _date = DateFormat('MMM dd, yyyy');

  static Future<Uint8List> generate({
    required ProfileModel store,
    required CustomerModel customer,
    required List<TransactionModel> transactions,
  }) async {
    final pdf = pw.Document();
    final storeName = store.storeName ?? 'Ang Aming Tindahan';
    final generatedOn = DateFormat('MMMM dd, yyyy').format(DateTime.now());

    // Compute running balance per row (oldest first for running total)
    final sorted = [...transactions]..sort((a, b) => a.date.compareTo(b.date));
    double running = 0;
    final rows = sorted.map((t) {
      final isUtang = t.type == 'utang';
      final displayAmount = isUtang ? t.totalWithInterest : t.amount;
      if (isUtang) {
        running += displayAmount;
      } else {
        running -= displayAmount;
      }
      if (running < 0) running = 0;
      return _RowData(t, displayAmount, running);
    }).toList();

    // Total outstanding (last running balance)
    final totalOutstanding = rows.isEmpty ? 0.0 : rows.last.balance;

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        header: (context) => _buildHeader(storeName, generatedOn),
        footer: (context) => _buildFooter(context),
        build: (context) => [
          _buildCustomerInfo(customer),
          pw.SizedBox(height: 16),
          _buildTable(rows),
          pw.SizedBox(height: 20),
          _buildTotalBox(totalOutstanding),
        ],
      ),
    );

    return pdf.save();
  }

  static pw.Widget _buildHeader(String storeName, String generatedOn) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  storeName,
                  style: pw.TextStyle(
                    fontSize: 18,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColor.fromHex('#1E88E5'),
                  ),
                ),
                pw.Text(
                  'STATEMENT OF ACCOUNT',
                  style: pw.TextStyle(
                    fontSize: 11,
                    letterSpacing: 1.5,
                    color: PdfColors.grey700,
                  ),
                ),
              ],
            ),
            pw.Text(
              'Date: $generatedOn',
              style: pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
            ),
          ],
        ),
        pw.SizedBox(height: 8),
        pw.Divider(color: PdfColor.fromHex('#1E88E5'), thickness: 1.5),
        pw.SizedBox(height: 4),
      ],
    );
  }

  static pw.Widget _buildFooter(pw.Context context) {
    return pw.Column(
      children: [
        pw.Divider(color: PdfColors.grey400),
        pw.SizedBox(height: 4),
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'Generated by Utang Tracker',
              style: pw.TextStyle(fontSize: 9, color: PdfColors.grey500),
            ),
            pw.Text(
              'Page ${context.pageNumber} of ${context.pagesCount}',
              style: pw.TextStyle(fontSize: 9, color: PdfColors.grey500),
            ),
          ],
        ),
      ],
    );
  }

  static pw.Widget _buildCustomerInfo(CustomerModel customer) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        color: PdfColors.grey100,
        borderRadius: pw.BorderRadius.circular(6),
      ),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text('CUSTOMER',
                    style: pw.TextStyle(
                        fontSize: 8,
                        color: PdfColors.grey600,
                        letterSpacing: 1)),
                pw.SizedBox(height: 2),
                pw.Text(customer.name,
                    style: pw.TextStyle(
                        fontSize: 14, fontWeight: pw.FontWeight.bold)),
                if (customer.phone != null && customer.phone!.isNotEmpty)
                  pw.Text(customer.phone!,
                      style: pw.TextStyle(
                          fontSize: 10, color: PdfColors.grey700)),
                if (customer.address != null && customer.address!.isNotEmpty)
                  pw.Text(customer.address!,
                      style: pw.TextStyle(
                          fontSize: 10, color: PdfColors.grey700)),
              ],
            ),
          ),
          if (customer.creditLimit != null && customer.creditLimit! > 0)
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.end,
              children: [
                pw.Text('CREDIT LIMIT',
                    style: pw.TextStyle(
                        fontSize: 8,
                        color: PdfColors.grey600,
                        letterSpacing: 1)),
                pw.SizedBox(height: 2),
                pw.Text(
                  '₱${_money.format(customer.creditLimit)}',
                  style: pw.TextStyle(
                      fontSize: 12, fontWeight: pw.FontWeight.bold),
                ),
              ],
            ),
        ],
      ),
    );
  }

  static pw.Widget _buildTable(List<_RowData> rows) {
    const headerStyle = pw.TextStyle(color: PdfColors.white);
    const cellStyle = pw.TextStyle(fontSize: 9);
    const cellCenter = pw.TextAlign.center;
    const cellRight = pw.TextAlign.right;

    if (rows.isEmpty) {
      return pw.Center(
        child: pw.Text('Walang transaksyon.',
            style: pw.TextStyle(color: PdfColors.grey500)),
      );
    }

    return pw.Table(
      border: pw.TableBorder(
        horizontalInside: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
      ),
      columnWidths: {
        0: const pw.FlexColumnWidth(2.2), // Date
        1: const pw.FlexColumnWidth(1.5), // Type
        2: const pw.FlexColumnWidth(2),   // Amount
        3: const pw.FlexColumnWidth(1.8), // Interest
        4: const pw.FlexColumnWidth(2),   // Balance
      },
      children: [
        // Header row
        pw.TableRow(
          decoration: pw.BoxDecoration(color: PdfColor.fromHex('#1E88E5')),
          children: [
            _cell('Date', style: headerStyle),
            _cell('Type', style: headerStyle, align: cellCenter),
            _cell('Amount', style: headerStyle, align: cellRight),
            _cell('Interest', style: headerStyle, align: cellRight),
            _cell('Balance', style: headerStyle, align: cellRight),
          ],
        ),
        // Data rows
        ...rows.map((r) {
          final isUtang = r.transaction.type == 'utang';
          final typeColor =
              isUtang ? PdfColor.fromHex('#E53935') : PdfColor.fromHex('#43A047');
          final overdueStyle = r.transaction.isOverdue
              ? pw.TextStyle(fontSize: 9, color: PdfColors.red)
              : cellStyle;

          return pw.TableRow(
            children: [
              pw.Padding(
                padding:
                    const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 5),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(_date.format(r.transaction.date), style: cellStyle),
                    if (r.transaction.description != null)
                      pw.Text(r.transaction.description!,
                          style: pw.TextStyle(
                              fontSize: 8, color: PdfColors.grey600)),
                    if (r.transaction.dueDate != null)
                      pw.Text(
                        'Due: ${_date.format(r.transaction.dueDate!)}',
                        style: overdueStyle.copyWith(fontSize: 8),
                      ),
                  ],
                ),
              ),
              _cell(
                isUtang ? 'Utang' : 'Bayad',
                style: pw.TextStyle(
                    fontSize: 9,
                    fontWeight: pw.FontWeight.bold,
                    color: typeColor),
                align: cellCenter,
              ),
              _cell(
                '₱${_money.format(r.displayAmount)}',
                style: pw.TextStyle(
                    fontSize: 9,
                    color: typeColor,
                    fontWeight: pw.FontWeight.bold),
                align: cellRight,
              ),
              _cell(
                r.transaction.interestAmount > 0
                    ? '₱${_money.format(r.transaction.interestAmount)}'
                    : '—',
                style: pw.TextStyle(fontSize: 9, color: PdfColors.orange700),
                align: cellRight,
              ),
              _cell(
                '₱${_money.format(r.balance)}',
                style: cellStyle.copyWith(fontWeight: pw.FontWeight.bold),
                align: cellRight,
              ),
            ],
          );
        }),
      ],
    );
  }

  static pw.Widget _buildTotalBox(double total) {
    final hasDebt = total > 0;
    final bgColor =
        hasDebt ? PdfColor.fromHex('#FFEBEE') : PdfColor.fromHex('#E8F5E9');
    final textColor =
        hasDebt ? PdfColor.fromHex('#C62828') : PdfColor.fromHex('#2E7D32');

    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(horizontal: 16, vertical: 12),
      decoration: pw.BoxDecoration(
        color: bgColor,
        borderRadius: pw.BorderRadius.circular(6),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            hasDebt ? 'KABUUANG UTANG' : 'WALANG NATITIRANG UTANG',
            style: pw.TextStyle(
              fontSize: 11,
              fontWeight: pw.FontWeight.bold,
              color: textColor,
              letterSpacing: 0.5,
            ),
          ),
          pw.Text(
            '₱${_money.format(total)}',
            style: pw.TextStyle(
              fontSize: 16,
              fontWeight: pw.FontWeight.bold,
              color: textColor,
            ),
          ),
        ],
      ),
    );
  }

  static pw.Widget _cell(
    String text, {
    pw.TextStyle? style,
    pw.TextAlign align = pw.TextAlign.left,
  }) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 5),
      child: pw.Text(text, style: style, textAlign: align),
    );
  }
}

class _RowData {
  final TransactionModel transaction;
  final double displayAmount;
  final double balance;
  const _RowData(this.transaction, this.displayAmount, this.balance);
}
